start-all-container:
	docker-compose -f ./docker/docker-compose.yaml up -d

stop-all-container:
	docker-compose -f ./docker/docker-compose.yaml down

list-container:
	docker-compose -f ./docker/docker-compose.yaml ps